Service:
  RegionId: ap-southeast-1
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: '单机版'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::aliyun-computenest_quickstart-doccano-docker-compose }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: aliyun-computenest_quickstart-doccano-docker-compose
    ArtifactProperty:
      RegionId: ap-southeast-1
      Url: 'resources/artifact_resources/docker_compose.tar'
  Artifact_2:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-doccano-doccano-backend
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Public
  Artifact_3:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-rabbitmq
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_2.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_2.Tag}
      RepoType: Public
  Artifact_4:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-doccano-doccano-frontend
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_3.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_3.Tag}
      RepoType: Public
  Artifact_5:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-postgres
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_4.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_4.Tag}
      RepoType: Public
AcrImageBuilder:
  AcrImage_1:
    BuildType: DockerRepo
    DockerRepoUrl: doccano/doccano:backend
    RepoName: doccano/doccano
    Tag: backend
  AcrImage_2:
    BuildType: DockerRepo
    DockerRepoUrl: rabbitmq:3.10.7-alpine
    RepoName: rabbitmq
    Tag: 3.10.7-alpine
  AcrImage_3:
    BuildType: DockerRepo
    DockerRepoUrl: doccano/doccano:frontend
    RepoName: doccano/doccano
    Tag: frontend
  AcrImage_4:
    BuildType: DockerRepo
    DockerRepoUrl: postgres:13.3-alpine
    RepoName: postgres
    Tag: 13.3-alpine